name: CI + CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile 1
        run: echo Hello, world!
    
  DeployDev:
    name: Deploy to Dev 
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: 'http://dev.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 
Deploystaging:
    name: Deploy to Dev 
    needs: [Build]
    environment: 
      name: Development
      url: 'http://dev.myapp.com'
    steps:
     - name: Deploy
       run: echo I am deploying!
  .
